-- Secure authentication + RBAC upgrade
-- Chosen model: secure server-side session cookies.
-- Rationale: this app has dynamic organization-manager permissions that should take effect immediately
-- after admin/contact changes without waiting for JWT expiry or token refresh.

ALTER TABLE football_pool.users
  ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255),
  ADD COLUMN IF NOT EXISTS password_set_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS password_reset_token_hash VARCHAR(128),
  ADD COLUMN IF NOT EXISTS password_reset_expires_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS password_reset_requested_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS admin_flg BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS active_flg BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_ci
  ON football_pool.users (LOWER(email))
  WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS football_pool.user_session (
  session_id VARCHAR(64) PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES football_pool.users (id) ON DELETE CASCADE,
  session_token_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMP NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMP,
  ip_address VARCHAR(128),
  user_agent TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_user_session_token_hash
  ON football_pool.user_session (session_token_hash);

CREATE INDEX IF NOT EXISTS idx_user_session_user_id
  ON football_pool.user_session (user_id);

CREATE INDEX IF NOT EXISTS idx_user_session_expires_at
  ON football_pool.user_session (expires_at);

CREATE TABLE IF NOT EXISTS football_pool.organization_access_request (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES football_pool.organization (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES football_pool.users (id) ON DELETE CASCADE,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  request_note TEXT,
  review_note TEXT,
  requested_at TIMESTAMP NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMP,
  reviewed_by INTEGER REFERENCES football_pool.users (id) ON DELETE SET NULL,
  CONSTRAINT chk_org_access_request_status
    CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_org_access_request_unique_user_org
  ON football_pool.organization_access_request (organization_id, user_id);

CREATE INDEX IF NOT EXISTS idx_org_access_request_status_org
  ON football_pool.organization_access_request (organization_id, status);

-- Seed Jeff Pflanzer as an admin in every upgraded environment where his user already exists.
UPDATE football_pool.users
SET admin_flg = TRUE
WHERE LOWER(COALESCE(email, '')) = 'jeff.pflanzer@gmail.com'
   OR (
     LOWER(COALESCE(first_name, '')) = 'jeff'
     AND LOWER(COALESCE(last_name, '')) = 'pflanzer'
   );
